build: try node alpine 22 image to resolve dns lookup issue (#324)
currently the github oauth signin flow fails because of a dns resolution
error. let's try if this is related to the recent change of the docker
base image (`node:22-alpine` to `node:24-alpine`)

error message:

```
TypeError: fetch failed
    at async ah (.next/server/app/api/keystatic/[...params]/route.js:2:662)
    at async c (.next/server/app/api/keystatic/[...params]/route.js:5:1508)
    at async (.next/server/chunks/8258.js:20:1524)
    at async k (.next/server/app/api/keystatic/[...params]/route.js:5:4897)
    at async g (.next/server/app/api/keystatic/[...params]/route.js:5:5901) {
  [cause]: [Error: getaddrinfo EAI_AGAIN github.com] {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'github.com'
  }
}
``